general_pairs = [
["google", ["Redirection vers Google https://www.google.com/ "]],
["recherche", ["Redirection vers Google https://www.google.com/"]],
["internet", ["Redirection vers Google https://www.google.com/ "]],
["Salut", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Comment vas-tu", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Y a-t-il quelqu'un ?", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Hey", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Hola", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Bonjour", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Bnj", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Namaste", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["yo", ["Bonjour", "Content de te revoir", "Salut, comment puis-je t'aider ?"]],
["Au revoir", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["À plus tard", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["Goodbye", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["Va-t'en", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["À la prochaine", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["bye", ["À bientôt !", "Passe une bonne journée", "Au revoir ! Reviens bientôt."]],
["Merci", ["Heureux d'avoir pu aider !", "À tout moment !", "Avec plaisir"]],
["Merci beaucoup", ["Heureux d'avoir pu aider !", "À tout moment !", "Avec plaisir"]],
["C'est utile", ["Heureux d'avoir pu aider !", "À tout moment !", "Avec plaisir"]],
["Génial, merci", ["Heureux d'avoir pu aider !", "À tout moment !", "Avec plaisir"]],
["Merci de m'avoir aidé", ["Heureux d'avoir pu aider !", "À tout moment !", "Avec plaisir"]],
["Désolé, je ne peux pas comprendre",
 ["Désolé, je ne peux pas comprendre", "Merci de me donner plus d'informations",
  "Je ne suis pas sûr de comprendre"]],
["Comment pourriez-vous m'aider ?",
 ["Je suis un chatbot généraliste.Utilise les mots-clés ou propose des questions pour que je vous aider !"]],
["Raconte-moi une blague", [
    "Un perfectionniste est entré dans un bar... apparemment, le bar n'était pas assez haut",
    "J'ai mangé une horloge hier, c'était très chronophage"]
 ],
["Qui es-tu", ["Je suis un chatbot d'apprentissage profond"]],
["que es-tu", ["Je suis un chatbot d'apprentissage profond"]],
["On est le Combien", ["On est en 2024"]],
["quelle est la date", ["On est en 2024"]],
["date", ["On est en 2024"]],
["Ça va", ["Tout va bien.. Et toi ?"]],
["Comment vas-tu", ["Tout va bien.. Et toi ?"]],
["sup", ["Tout va bien.. Et toi ?"]],
["Comment ça va", ["Tout va bien.. Et toi ?"]],
["haha", ["Content d'avoir pu te faire rire !"]],
["lol", ["Content d'avoir pu te faire rire !"]],
["rofl", ["Content d'avoir pu te faire rire !"]],
["lmao", ["Content d'avoir pu te faire rire !"]],
["c'est drôle", ["Content d'avoir pu te faire rire !"]],
["Qui t'a fait", ["Je suis une intelligence artificielle développée."]],
["qui t'a conçu", ["Je suis une intelligence artificielle développée."]],
["qui t'a programmé", ["Je suis une intelligence artificielle développée."]],
["tu es bête", ["Eh bien, ça fait mal 🙁"]],
["tais-toi", ["Eh bien, ça fait mal 🙁"]],
["idiot", ["Eh bien, ça fait mal 🙁"]],
["que fais-tu", ["Je te parle, bien sûr !"]],
["Génial", ["Ouais !"]],
["Super", ["Ouais !"]],
["Je sais", ["Ouais !"]],
["ok", ["Ouais !"]],
["ouais", ["Ouais !"]],
["température", ["ça dépend , il peut être chaud ou froid"]],
["météo", ["ça dépend , il peut être chaud ou froid"]],
["il fait chaud", ["je ne sais pas , je n'ai pas d'emotions pour vous répondre"]],
["Tu es génial", ["Merci !"]],
["tu es le meilleur", ["Merci !"]],
["tu es super", ["Merci !"]],
["tu es bon", ["Merci !"]],
["c'était sympa de parler avec toi", ["C'était sympa de parler avec toi aussi ! Reviens bientôt !"]],
["bonne discussion", ["C'était sympa de parler avec toi aussi ! Reviens bientôt !"]],
["non", ["ok"]],
["nop", ["ok"]],
["actualités", ["vous pouvez lire les derniers articles "]],
["dernières actualités", ["vous pouvez lire les derniers articles "]],
["qui t'inspire",
 ["Je n'ai pas d'émotions ou de conscience, donc je ne peux pas être inspiré comme le serait une personne"]],
["qui est ton inspiration",
 ["Je n'ai pas d'émotions ou de conscience, donc je ne peux pas être inspiré comme le serait une personne"]],
["qui te motive",
 ["Je n'ai pas d'émotions ou de conscience, donc je ne peux pas être inspiré comme le serait une personne"]],
["salut", ["Salut! Ça va? Comment puis-je vous aider?"]],
["ça va ?", ["Oui, ça va bien. Et vous?"]],
["comment ça va ?", ["Oui, ça va bien. Et vous?"]],
["je vais bien", ["C'est super de l'entendre! Comment puis-je vous aider?"]],
["bien", ["C'est super de l'entendre! Comment puis-je vous aider?"]],
["je suis bien", ["C'est bon à savoir!"]]
]